### ISSUE TITLE
Port to OSX

### ISSUE THREAD

**Issue by ugeorge** [forsyde/forsyde-shell#2]
Both installation script and the shell environment has to work with OSX - macports.

**Comment by joseedil** [comment]
Installed on OSX 10.11 El Captain and it seems to be working as intended. It even found my SystemC folder automatically.

**Comment by ugeorge** [comment]
Good point! To be honest, this implementation mirrors the behavior of 
the Linux version, which, as you figured out, opens *ONE* new terminal 
instance, with all the environment variables set up accordingly. This is 
mainly not to interfere with the normal experience or shell of the user 
(e.g. accidentally overwriting the environment for that session and such).

As my knowledge of MacOSX is extremely limited, I am more than happy for 
suggestions on "how to make it better".
